(define (fib n)
	(define (even? n)
    (= (remainder n 2) 0)
  )
	(define (fib-ite1 a b p q count)
	  (cond ((= count 0) b)
		  ((even? count) (fib-ite1 a b (+ (* p p) (* q q)) (+ (* q q) (* 2 p q)) (/ count 2)))
			(else (fib-ite1 (+ (* b q) (* a q) (* a p)) (+ (* b p) (* a q)) p q (- count 1)))
	  )
	)
	(fib-ite1 1 0 0 1 n)
)
