;fixed-point
(define (fixed-point f guess)
  (define tolerance 0.000001)
	(define (abs y)
    (cond ((< y 0) (- 0 y))
      (else y)
    )
  )
  (define (close-enough? v1 v2)
    (if (< (/ (abs (- v1 v2)) v2) tolerance) #t #f)
  )
  (define (try g)
    (let ((next (f g))) 
		  (if (close-enough? g next) next (try next))
    )
  ) 
	(try guess)
)

; compute y^2 = x -> y = ?
(define (sqrt0 x)
  (fixed-point (lambda (y) (/ (+ y (/ x y)) 2.0)) 1.0)
)

; 1.36 compute y^y = x -> y = ?
(define (xx x)
  (define (fixed-point f guess)
    (define tolerance 0.000001)
	  (define (abs y)
      (cond ((< y 0) (- 0 y))
        (else y)
      )
    )
    (define (close-enough? v1 v2)
      (if (< (/ (abs (- v1 v2)) v2) tolerance) #t #f)
    )
		(define (discre t m n)
		  (newline)
			(display m)
			(t n)
		)
    (define (try g)
      (let ((next (f g))) 
		    (if (close-enough? g next) next (discre try g next))
      )
    ) 
	  (try guess)
  )
  (fixed-point (lambda (y) (/ (+ y (/ (log x) (log y))) 2.0)) 2.0)
)

(define (average-damp f)
  (define (average a b)
    (/ (+ a b) 2.0)
  )
	(lambda (x) (average x (f x)))
)

(define (sqrt1 x)
  (fixed-point (average-damp (lambda (y) (/ x y))) 1.0)
)

(define (cube-root x)
  (fixed-point (average-damp (lambda (y) (/ x (* y y)))) 1.0)
)


