(define (sqrt x)
  (define (average y z)
    (/ (+ y z) 2.0)
  )
  (define (abs y)
    (cond ((< y 0) (- 0 y))
      (else y)
    )
  )
  (define (square y)
    (* y y)
  )
  (define (goodenough guess)
    (< (abs (- (square guess) x)) 0.001)
  )  
  (define (sqrtiter guess)
    (if (goodenough guess) guess
      (sqrtiter (average guess (/ x guess)))
    )
  )
  (sqrtiter 1.0)
)