(define (memq1 item ls)
  (cond ((null? ls) #f)
        ((eq? item (car ls)) ls)
        (else (memq1 item (cdr ls)))
  )
)

(define (my-equal x y)
  (or (eq? x y) 
      (and (and (pair? x) (pair? y))
           (eq? (car x) (car y)) 
           (my-equal (cdr x) (cdr y))
      )
  )
)
